game_portal/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# from users import views as user_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('', include('bulletin_board.urls')),
    path('accounts/', include('allauth.urls')),
    path('sign/', include('sign.urls')),
    # path('protect/', include('protect.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sign/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import BaseRegisterView #, upgrade_me

urlpatterns = [
    path('login/',
         LoginView.as_view(template_name='sign/login.html'),
         name='login'),
    path('logout/',
         LogoutView.as_view(template_name='sign/logout.html'),
         name='logout'),
    path('signup/',
         BaseRegisterView.as_view(template_name='sign/signup.html'),
         name='signup'),
    # path('upgrade/', upgrade_me, name='upgrade')
]

bulletin_board/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from ckeditor.fields import RichTextField



class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} Profile'

class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)
    subscribers = models.ManyToManyField(User, blank=True)

    def __str__(self):
        return self.name

class Bulletin(models.Model):
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)
    header = models.CharField(max_length=255)
    text = RichTextField(blank=True, null=True)
    date = models.DateTimeField(auto_now_add=True)
    category = models.ManyToManyField(Category, through = 'BulletinToCategory')


    def __str__(self):
        return f'{self.header} {self.text[:10]} {self.date}'

    def get_absolute_url(self):
        return reverse('bulletin', args=[str(self.pk)])

    def preview(self):
        return self.text[0:123] + '...'


class BulletinToCategory(models.Model):
    bulletin = models.ForeignKey(Bulletin, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

class Response(models.Model):
    text = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    bulletin = models.ForeignKey(Bulletin, on_delete=models.CASCADE)  # связь «один ко многим» с моделью Post
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)  # связь «один ко многим» с моделью Author
    accepted = models.BooleanField(default=False)

    class Meta:
        unique_together = ['bulletin', 'author']

    def __str__(self):
        return f'{self.author.user.username} - {self.text[:20]}'

    def get_absolute_url(self):
        return f'/response/{self.id}'


bulletin_board/forms.py
from django import forms
from .models import Bulletin, Category, Response
from ckeditor.widgets import CKEditorWidget

class BulletinForm(forms.ModelForm):

    text = forms.CharField(widget=CKEditorWidget())
    category = forms.ModelMultipleChoiceField(
        queryset=Category.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=True,
        error_messages={
            'required': 'Необходимо выбрать хотя бы одну категорию'
        }
    )

    class Meta:
        model = Bulletin
        fields = [
           'header',
           'text',
           'category',
       ]
        labels = {
            'header': 'Заголовок',
            'text': 'Текст',
            'category': 'Категория'
        }

class ResponseForm(forms.ModelForm):
    class Meta:
        model = Response
        fields = ('text',)

templates/bulletin.html
{% extends 'flatpages/default.html' %}


{% block title %}
News
{% endblock title %}

<!-- {% block nav %}
    {% if request.user.is_staff == True %}
        <li class="nav-item"><a class="nav-link active" aria-current="page" href="/">Профиль</a></li>  
        <li class="nav-item"><a class="nav-link active" aria-current="page" href="/news/articles/create/">Создать Статью</a></li>  
        <li class="nav-item"><a class="nav-link active" aria-current="page" href="/news/create/">Создать Новость</a></li>  
    {% else %}
        <li class="nav-item"><a class="nav-link active" aria-current="page" href="/sign/signup/">Регистрация</a></li>     
        <li class="nav-item"><a class="nav-link active" aria-current="page" href="/sign/login/">Авторизация</a></li>   
    {% endif%} 
{% endblock nav %} -->
    {% block content %}
        <div class="card   my-5 py-4 ">
            <div class="card-body text-center">
                <h1 class="font-weight-light">{{ bulletin.heading }}</h1>
                <h1>{{ bulletin.date|date:'d M Y' }} </h1>
            </div>
            <div class="card-footer">
                <p class="card-text">{{ bulletin.text|safe }}</p>
            </div>
            <div class="card-footer"><a class="btn btn-primary btn-sm" href="{% url 'bulletin_delete' bulletin.pk %}">Удалить</a>
<a class="btn btn-primary btn-sm" href="{% url 'bulletin_edit' bulletin.pk %}">Редактировать</a></div>
        <h3>Оставить Отклик</h3>
    <form method="post" action="{% url 'response_create' bulletin.pk %}">
        {% csrf_token %}
        {{ response_form.as_p }}
        <button type="submit">Отправить</button>
    </form>
        </div>
    {% endblock content %}

templates/bulletin_create.html
{% extends 'flatpages/default.html' %}
{% load static %}
<script src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>

{% block title %}
News portal
{% endblock title %}

{% block content %}
<div class="card my-5 py-4">
    <div class="card-body text-center">
        <h1 class="font-weight-light">Создать публикацию</h1>
    </div>
    <div class="card-footer text-center">
        <form action="" method="post">
            {% csrf_token %}
            {{ form.media }}
           <p> {{ form.header }}</p>
            <p>{{ form.text|safe }}</p>
<!--            <textarea name="text" id="id_text"></textarea>-->
            <p>{{ form.category }}</p>
            <input class="btn btn-primary btn-sm" type="submit" value="Save" />
        </form>
    </div>
</div>
{% endblock content %}
<script>
    var editor = CKEDITOR.replace('id_text', {
        toolbarGroups: [
            { name: 'document', groups: ['mode', 'document', 'doctools'] },
            { name: 'clipboard', groups: ['clipboard', 'undo'] },
            { name: 'editing', groups: ['find', 'selection', 'spellchecker'] },
            { name: 'forms' },
            '/',
            { name: 'basicstyles', groups: ['basicstyles', 'cleanup'] },
            { name: 'paragraph', groups: ['list', 'indent', 'blocks', 'align', 'bidi'] },
            { name: 'links' },
            { name: 'insert' },
            '/',
            { name: 'styles' },
            { name: 'colors' },
            { name: 'tools' },
            { name: 'others' },
            { name: 'about' }
        ],
        // Remove the redundant buttons from toolbar groups defined above
        removeButtons: 'Underline,Strike,Subscript,Superscript,Anchor,Styles,Specialchar'
    });
</script>

templates/bulletin_created_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Уведомление</title>
</head>
<body>
    <h2>Здравствуйте! Новая<a href="{{ link }}"> статья</a> в вашем любимом разделе!</h2>
        <p>{{ text|safe }}</p>
</body>
</html>

templates/bulletin_delete.html
{% extends 'flatpages/default.html' %}

{% block title %}
News portal
{% endblock title %}



{% block content %}

<div class="card   my-5 py-4 ">
    <div class="card-body text-center">
        <form action="" method="post">
            {% csrf_token %}
            <p>Удаление публикации "{{ bulletin }}"?</p>
            <input class="btn btn-primary btn-sm " type="submit" value="Delete" />
        </form>
    </div>

</div>


{% endblock content %}

templates/bulletin_edit.html
{% extends 'flatpages/default.html' %}

{% block title %}
News portal
{% endblock title %}



{% block content %}
<div class="card   my-5 py-4 ">
    <div class="card-body text-center">
        <h1 class="font-weight-light"> {{bulletin.header}} Изменение публикации</h1>
    </div>  
    <div class="card-footer text-center">
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="btn btn-primary btn-sm" type="submit" value="Save" />
        </form>
       
    </div>
</div> 
{% endblock content %}

templates/bulletins.html
{% extends 'flatpages/default.html' %}



{% block title %}
News portal
{% endblock title %}



{% block content %}
    <div class="card text-white bg-secondary my-5 py-4 text-center">
        <div class="card-body"><p class="text-white m-0">Всего публикаций: {{ bulletins|length}}</p>  </div>
        
    </div>
<!-- Content Row-->
    <div class="row gx-4 gx-lg-5">
        {% if bulletins %}
            {% for bulletin in bulletins %}
        <div class="col-md-4 mb-5">
            <div class="card h-100">
                <div class="card-body">
                    <h5 class="card-title">{{ bulletin.header }} </h5>
                    <h4 class="card-title">{{ bulletin.date|date:'d M Y' }}</h4>
                    <p class="card-text">{{ bulletin.text|striptags|truncatewords:20 }}</p>
                    <p class="card-text">
    {% for category in bulletin.bulletintocategory_set.all %}
                        <a href="{% url 'category_list' category.category.id %}">{{ category.category.name }}</a>
       {% if not forloop.last %}, {% endif %}
    {% empty %}
        Нет категорий
    {% endfor %}
</p>

                </div>
                <div class="card-footer"><a class="btn btn-primary btn-sm" href={{bulletin.get_absolute_url}}>Читать дальше</a></div>
            </div>
        </div>
            {% endfor %}       
        {% else %}
        <div class="card   my-5 py-4 ">
            <div class="card-body text-center">
                <h1 class="font-weight-light">Постов нет!</h1>    
            </div>  
        </div> 
        {% endif %}
        <div class="card text-white bg-secondary my-5 py-4 text-center"><p>
        {# Добавляем пагинацию на страницу #}

        {# Информация о предыдущих страницах #}
        {% if page_obj.has_previous %}
            <a class=" text-white " href="?page=1">1</a>
            {% if page_obj.previous_page_number != 1 %}
                ...
                <a class=" text-white " href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
            {% endif %}
        {% endif %}
     
        {# Информация о текущей странице #}
        {{ page_obj.number }}
     
        {# Информация о следующих страницах #}
        {% if page_obj.has_next %}
            <a class=" text-white " href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
            {% if paginator.num_pages != page_obj.next_page_number %}
                ...
                <a class=" text-white " href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
            {% endif %}
        {% endif %}
    </p></div>
</div>
{% endblock content %}


templates/category_list.html
{% extends 'flatpages/default.html' %}



{% block title %}
News portal
{% endblock title %}



{% block content %}
    <div class="card text-white bg-secondary my-5 py-4 text-center">
        <div class="card-body"><p class="text-white m-0">Всего публикаций: {{ posts|length}}</p>  </div>
        <div class="card-body"><p class="text-white m-0">Категория: {{ category}}</p>  </div>
    </div>
<!-- Content Row-->
    <div class="row gx-4 gx-lg-5">
         {% if is_not_subscribed %}
        <p class="text-center"><a href="{% url 'subscribe' category.id %}" class="btn btn-secondary btn-sm">Подписаться</a></p>

        {% else %}
        <p class="text-center"><a href="{% url 'unsubscribe' category.id %}" class="btn btn-secondary btn-sm">Отписаться</a></p>
    {% endif %}
        {% if category_news_list %}
            {% for post in category_news_list %}
        <div class="col-md-4 mb-5">
            <div class="card h-100">
                <div class="card-body">
                    <h5 class="card-title">{{ post.heading }} </h5>
                    <h4 class="card-title">{{ post.date|date:'d M Y' }}</h4>
                    <p class="card-text">{{ post.text|truncatewords:20 }}</p>
                    <p class="card-text">{% for category in post.category.all %}
                    <a href="{% url 'category_list' category.id %}">{{ category }}</a>
                {% endfor %}
                    </p>
                </div>
                <div class="card-footer"><a class="btn btn-primary btn-sm" href={{bulletin.get_absolute_url}}>Читать дальше</a></div>
            </div>
        </div>
            {% endfor %}
        {% else %}
        <div class="card   my-5 py-4 ">
            <div class="card-body text-center">
                <h1 class="font-weight-light">Постов нет!</h1>
            </div>
        </div>
        {% endif %}
        <div class="card text-white bg-secondary my-5 py-4 text-center"><p>
        {# Добавляем пагинацию на страницу #}

        {# Информация о предыдущих страницах #}
        {% if page_obj.has_previous %}
            <a class=" text-white " href="?page=1">1</a>
            {% if page_obj.previous_page_number != 1 %}
                ...
                <a class=" text-white " href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
            {% endif %}
        {% endif %}

        {# Информация о текущей странице #}
        {{ page_obj.number }}

        {# Информация о следующих страницах #}
        {% if page_obj.has_next %}
            <a class=" text-white " href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
            {% if paginator.num_pages != page_obj.next_page_number %}
                ...
                <a class=" text-white " href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
            {% endif %}
        {% endif %}
    </p></div>
</div>
{% endblock content %}


templates/response_delete.html
{% extends 'flatpages/default.html' %}

{% block title %}
Удалить отклик
{% endblock title %}

{% block content %}
    <h1>Удалить отклик?</h1>
    <p>{{ object.text }}</p>
    <form method="post">
        {% csrf_token %}
        <input type="submit" value="Удалить">
        <a href="{% url 'author_response_list' author_id=request.user.profile.id %}">Отмена</a>
    </form>
{% endblock %}

templates/response_list.html
{% extends 'flatpages/default.html' %}


{% block title %}
News
{% endblock title %}





{% block content %}
  <h1>Ответы на объявление: {{ bulletin.title }}</h1>

  {% for response in responses %}
    <div>
      <p>Автор: {{ response.author.user.username }}</p>
      <p>{{ response.content }}</p>
      <!-- Здесь можно добавить форму для ответа на данный ответ -->
    </div>
  {% endfor %}

  <!-- Форма для создания нового ответа -->
  <form method="post" action="{% url 'response_create' bulletin.pk %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Отправить ответ</button>
  </form>


    {% endblock content %}

templates/response_update.html
{% extends 'flatpages/default.html' %}

{% block title %}
Принять отклик
{% endblock title %}

{% block content %}
    <h1>Принять отклик?</h1>
    <p>{{ object.text }}</p>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Принять">
        <a href="{% url 'author_response_list' author_id=request.user.profile.id %}">Отмена</a>
    </form>
{% endblock %}

templates/subscribe.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Уведомление</title>
</head>
<body>
<h2>Здравствуйте!{{ user.username }} Вы подписались на {{ category.name }} </h2>
    <p>{{ text }}</p>
</body>
</html>

templates/weekly_notifications_email.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Weekly Notifications</title>
</head>
<body>
    <h1>Новости для вас в разделе: {{ category }}</h1>
    <ul>
    {% for bulletin in bulletins %}
        <li>
            <h2>{{ bulletin.heading }}</h2>
            <p>{{ bulletin.preview }}</p>
            <p>Автор: {{ bulletin.author.user.username }}</p>
            <a href="{{ link }}{{ bulletin.pk }}">Прочитай больше</a><br>
        </li>
    {% endfor %}
    </ul>
</body>
</html>

templates/your_template.html
{% extends 'flatpages/default.html' %}

{% block title %}
Ответы на объявления
{% endblock title %}

{% block content %}
    <h1>Ответы на объявления пользователя</h1>
    <a href="{% url 'author_response_list' author_id=request.user.profile.id %}">Все отклики</a>
    <a href="{% url 'author_response_list' author_id=request.user.profile.id %}?accepted=True">Принятые отклики</a>
    <a href="{% url 'author_response_list' author_id=request.user.profile.id %}?accepted=False">Непринятые отклики</a>

    {% for response in object_list %}
        <div>
            <h2>Объявление: {{ response.bulletin.header }}</h2>
            <p>{{ response.text }}</p>
            <p>От: {{ response.author.user.username }}</p>
            {% if response.accepted %}
                <p>Принят</p>
            {% else %}
                <a href="{% url 'response_update' pk=response.pk %}">Принять отклик</a>
                <a href="{% url 'response_delete' pk=response.pk %}">Отклонить отклик</a>
            {% endif %}
        </div>
    {% empty %}
        <p>Нет ответов на объявления.</p>
    {% endfor %}
{% endblock %}